---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: jhcook/macos-sierra

suites:
  - name: blockheads
    run_list:
      - recipe[blockheads-server::default]
    attributes:
