name 'blockheads_server'
maintainer 'Erin L. Kolp'
maintainer_email 'erinlkolpfoss@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures blockheads_server'
long_description 'Installs/Configures blockheads_server'
version '17.11.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
issues_url 'https://github.com/erinlkolp/blockheads_server/issues'
source_url 'https://github.com/erinlkolp/blockheads_server'
